projectspirit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spiritdashboard.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

# This is discouraged, but we're using it for the sake of simplicity
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spiritdashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'spiritdashboard'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='index'),
    path('dashboard/', views.dashboard),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='spiritdashboard/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('claim/<str:key>/', views.claim_key, name='claim_key'),
    path('claim/', views.claim_key, name='claim_key_post'),
    path('user_leaderboard/', views.UserLeaderboard.as_view(), name='user_leaderboard'),
    path('grade_leaderboard/', views.GradeLeaderboard.as_view(), name='grade_leaderboard'),
    path('completed/', views.completed, name='completed'),
    path('privacy/', views.privacy_policy, name='privacy_policy')
]

spiritdashboard/models.py
import random
import string
import datetime

import math

from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils import timezone
import pagan


def generate_random_key():
    chars = string.ascii_lowercase + string.ascii_uppercase + string.digits
    return ''.join(random.choice(chars) for _ in range(10))


def generate_profile_picture():
    img = pagan.Avatar(generate_random_key(), pagan.SHA512)
    return img


class Grade(models.Model):

    name = models.CharField(max_length=50)
    points = models.IntegerField(default=0)

    def rank(self):
        aggregate = Grade.objects.filter(points__gt=self.points).aggregate(
            ranking=models.Count('points'))
        return aggregate['ranking'] + 1

    def __str__(self):
        return self.name

class CaseInsensitiveUserManager(UserManager):
    def get_by_natural_key(self, username):
        case_insensitive_username_field = '{}__iexact'.format(self.model.USERNAME_FIELD)
        return self.get(**{case_insensitive_username_field: username})

class User(AbstractUser):
    objects = CaseInsensitiveUserManager()
    points = models.IntegerField(default=0)
    grade = models.ForeignKey(Grade, on_delete=models.SET_NULL, null=True)

    health = models.IntegerField(default=100)
    health_max = models.IntegerField(default=100)

    total_xp = models.IntegerField(default=0)

    def rank(self):
        aggregate = User.objects.filter(points__gt=self.points).aggregate(
            ranking=models.Count('points'))
        return aggregate['ranking'] + 1

    def health_percent(self):
        return math.floor((self.health / self.health_max) * 100)

    def level(self):
        prev_level = 1  
        while self.total_xp > User.total_xp_for_level(prev_level):
            prev_level += 1
        if self.total_xp != User.total_xp_for_level(prev_level):
            prev_level -= 1
        return prev_level

    def xp_toward_next_level(self):
        return self.total_xp - User.total_xp_for_level(self.level())

    def xp_percent(self):
        return math.floor(self.xp_toward_next_level() / User.total_xp_for_level(self.level()+1) * 100)

    @staticmethod
    def xp_for_level(level):
        if level <= 1:
            return 0
        return (level - 1) * 5

    @staticmethod
    def total_xp_for_level(level):
        return level/2 * ((level - 1) * 5)


class Mission(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    location = models.CharField(max_length=50)
    value = models.IntegerField(default=0)
    xp_points = models.IntegerField(default=5)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)

    def is_future(self):
        return self.start_time > timezone.now()

    def is_expired(self):
        return self.end_time < timezone.now()

    def is_completed_by_user(self, user):
        return CompletedMission.objects.filter(mission=self, user=user) > 0

    def __str__(self):
        return self.title


class CompletedMission(models.Model):
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.mission.title + ' by ' + self.user.username


class MissionKey(models.Model):
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE)
    key = models.CharField(max_length=10, unique=True,
                           default=generate_random_key)
    one_use = models.BooleanField(default=False)
    times_used = models.IntegerField(default=0)

    def __str__(self):
        return self.mission.title + ': ' + self.key

spiritdashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Grade, User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, help_text='Please enter your school email address.')
    grade = forms.ModelChoiceField(queryset=Grade.objects.all())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'grade')

spiritdashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

from .models import Mission, CompletedMission, MissionKey, User, Grade
from django.utils import timezone
from django.views.generic import ListView
import pagan
from .forms import SignUpForm

from django.core.files.storage import default_storage

from projectspirit.settings import MEDIA_DIR, MEDIA_URL

import base64
from io import BytesIO

import datetime


def index(request):
    return HttpResponse('Hi')


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)

            user.save()

            login(request, user)
            return redirect('spiritdashboard:dashboard')
    else:
        form = SignUpForm()

    context = {'form': form}
    return render(request, 'spiritdashboard/register.html', context=context)


@login_required
def dashboard(request):

    # Generate avatar base64
    avatar = pagan.Avatar(request.user.username, pagan.SHA512)
    buffered = BytesIO()
    avatar.img.save(buffered, format='PNG')
    avatar_base64 = base64.b64encode(buffered.getvalue()).decode('ascii')

    context = {
        'missions': Mission.objects.filter(end_time__gte=timezone.now()).exclude(completedmission__user=request.user).order_by('start_time'),
        'completed_missions': Mission.objects.filter(completedmission__user=request.user),
        'grade': request.user.grade,
        'avatar_base64': avatar_base64
    }
    return render(request, 'spiritdashboard/dashboard.html', context=context)


@login_required
def claim_key(request, key=None):

    if key is None and request.method == 'POST' and 'key' in request.POST.keys():
        key = request.POST['key']

    # Validates key string
    if len(key) == 10 and len(MissionKey.objects.filter(key=key)) > 0:
        mission_key = MissionKey.objects.filter(key=key)[0]
        mission = mission_key.mission

        # Checks if mission is not expired or in the future, and that it has not been completed before
        if not mission.is_future() and not mission.is_expired() and not CompletedMission.objects.filter(mission=mission, user=request.user):

            if mission_key.one_use and mission_key.times_used > 0:
                return HttpResponseBadRequest(reason='Key provided has already been used.')

            # Creates CompletedMission object and saves it to database
            completed_mission = CompletedMission(
                mission=mission, user=request.user)
            completed_mission.save()

            # Adds points for the user
            request.user.points += mission.value

            # Adds XP points for the user
            request.user.total_xp += mission.xp_points

            # Adds points for the user's grade (if it exists)
            if request.user.grade is not None:
                request.user.grade.points += mission.value

            request.user.save()
            request.user.grade.save()

            # Increases times_used of key
            mission_key.times_used += 1
            mission_key.save()

            return render(request, 'spiritdashboard/completed.html', context={'mission': mission})
    
    return HttpResponseBadRequest(reason='Invalid key, or you have already completed the mission.')


def completed(request):
    return render(request, 'spiritdashboard/completed.html')


class UserLeaderboard(ListView):
    model = User
    template_name = 'spiritdashboard/leaderboards/user.html'
    queryset = User.objects.order_by('-points')[:10]


class GradeLeaderboard(ListView):
    model = Grade
    template_name = 'spiritdashboard/leaderboards/grade.html'
    queryset = Grade.objects.order_by('-points')[:10]

def privacy_policy(request):
    return render(request, 'spiritdashboard/privacy_policy.html')

spiritdashboard/templates/spiritdashboard/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134715036-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-134715036-1');
    </script>


    <link rel="stylesheet" href="{% static 'css/mint-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/projectspirit.css' %}">


    <title>SMUS Go</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <br>
                <nav class="navbar navbar-dark bg-primary">
                    <a class="navbar-brand" href="{% url 'spiritdashboard:dashboard' %}">🏆 <b>SMUS Go</b></a>
                    <span class="navbar-text">
                    {% if user.is_authenticated %}
                        Signed in as {{ user.username }}.
                    {% else %}
                        A game, but even better.
                    {% endif %}
                    </span>
                </nav>
                <br>
                {% block content %}
                {% endblock %}
                <hr>
                <footer class="text-center">
                <p><small>Made with 💖 by Rashid & Garry | <a href="https://github.com/rashidx/smus-go">Contribute</a> | <a href="{% url 'spiritdashboard:privacy_policy' %}">Privacy Policy</a> | <a href="{% url 'spiritdashboard:logout' %}">Logout</a></small></p>
                </footer>
                <hr>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

spiritdashboard/templates/spiritdashboard/completed.html
{% extends 'spiritdashboard/base.html' %}

{% load static %}

{% block content %}

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col text-center">
                <img src="{% static 'img/completed.svg'%}" class="img-responsive">
                <br><br>
                <h4>Mission Completed!</h4>
            </div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-3 text-center">
                <img src="{% static 'img/npc_bailey.png'%}" class="img-responsive" width="100%">

            </div>
            <div class="col-9">
                <p>Warrior,<br>You have completed the mission "{{ mission.title }}". As promised, I have added <b>{{ mission.value }} gems</b> to
                    your vault.</p>
            </div>
        </div>

    </div>
</div>

{% endblock %}

spiritdashboard/templates/spiritdashboard/dashboard.html
{% extends 'spiritdashboard/base.html' %}

{% load static %}


{% block content %}
<div class="card">
    <div class="card-header">
        Your Profile
    </div>
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-4 text-center right-divider">
                <img class="img-fluid" src="data:image/png;charset=utf-8;base64,{{ avatar_base64 }}">
            </div>
            <div class="col">

                <p><b>{{ user.first_name }} {{ user.last_name }}</b><br>
                    <small>@{{ user.username }} &#183; Level {{ user.level }} Warrior</small></p>

                <!-- Health -->
                <div class="row align-items-center text-center">
                    <div class="col-2">
                        <img height="25px" src="{% static 'img/health.svg' %}">
                    </div>
                    <div class="col-10">
                        <div class="progress" style="height:25px">
                            <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated" role="progressbar"
                                style="width: {{ user.health_percent }}%" aria-valuenow="{{ user.health_percent }}" aria-valuemin="0" aria-valuemax="100"><b>{{ user.health_percent }}%</b></div>
                        </div>
                    </div>
                </div>

                <!-- Experience -->
                <div class="row align-items-center text-center">
                    <div class="col-2">
                        <img height="25px" src="{% static 'img/star.svg' %}">
                    </div>
                    <div class="col-10">
                        <div class="progress" style="height:25px">
                            <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated" role="progressbar"
                                style="width: {{ user.xp_percent }}%" aria-valuenow="{{ user.xp_percent }}" aria-valuemin="0" aria-valuemax="100"><b>{{ user.xp_percent }}%</b></div>
                        </div>
                    </div>
                </div>




            </div>
        </div>
    </div>
</div>
<br>
<div class="card">
    <div class="card-header">
        Claim A Key
    </div>
    <div class="card-body">
        <form method="post" action="{% url 'spiritdashboard:claim_key_post' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-8">
                <div class="form-group">
                    <input name="key" class="form-control" placeholder="Enter your key">
                </div>
            </div>
            <div class="col">
                <button type="submit" class="btn btn-primary btn-block">Claim</button>
            </div>
        </div>
        </form>
    </div>
</div>

<br>
<div class="card">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col">
                Your Stats
            </div>
            <div class="col">
                <a href="{% url 'spiritdashboard:user_leaderboard' %}" class="btn btn-primary btn-sm float-right">View
                    Leaderboard</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col text-center right-divider">
                <h6>Gems</h6>
                <h3><img src="{% static 'img/gem.svg' %}" class="img-responsive" width="25px"> {{ user.points }}</h3>
            </div>
            <div class="col text-center">
                <h6>Rank</h6>
                <h3><img src="{% static 'img/leaderboard.svg' %}" class="img-responsive" width="25px"> #{{ user.rank }}</h3>
            </div>
        </div>
    </div>
</div>
<br>
<div class="card">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col">
                {{ grade.name }} Stats
            </div>
            <div class="col">
                <a href="{% url 'spiritdashboard:grade_leaderboard' %}" class="btn btn-primary btn-sm float-right">View
                    Leaderboard</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col text-center right-divider">
                <h6>Gems</h6>
                <h3><img src="{% static 'img/gem.svg' %}" class="img-responsive" width="25px"> {{ grade.points }}</h3>
            </div>
            <div class="col text-center">
                <h6>Rank</h6>
                <h3><img src="{% static 'img/leaderboard.svg' %}" class="img-responsive" width="25px"> #{{ grade.rank }}</h3>
            </div>
        </div>
    </div>
</div>

<hr>
<h6>Missions</h6>
<div class="card">
    <div class="card-body">
        {% for mission in missions %}
        <div class="row align-items-center">

                <div class="col-1 text-center">
                        <img src="{% static 'img/sparkles.svg' %}" alt="" class="">
                    </div>

            <div class="col">

                <h6>{{ mission.title }}</h6>
                <p>{{ mission.description }}</p>
                <span class="badge badge-primary">{{ mission.location }}</span>

            </div>
            <div class="col-3 text-center">
                <h6>Gems</h6>
                <h2>{{ mission.value }}</h2>
            </div>
        </div>
        {% if not forloop.counter == missions|length %}
        <hr>
        {% endif %}
        {% endfor %}
    </div>
</div>

<hr>
<h6>Completed Missions</h6>
<div class="card">
    <div class="card-body">
        {% for mission in completed_missions %}
        <div class="row align-items-center">

                <div class="col-1 text-center">
                        <img src="{% static 'img/sparkles.svg' %}" alt="" class="">
                </div>

            <div class="col">

                <h6><s>{{ mission.title }}</s></h6>
                <p>{{ mission.description }}</p>
                <span class="badge badge-primary">{{ mission.location }}</span>

            </div>
            <div class="col-3 text-center">
                <p>Gems</p>
                <h2>{{ mission.value }}</h2>
            </div>
        </div>
        {% if not forloop.counter == completed_missions|length %}
        <hr>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

spiritdashboard/templates/spiritdashboard/login.html
{% extends 'spiritdashboard/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <h4>✨ New here?</h4>
  <p>SMUS Go is a game where you and your friends can compete to earn points, and your grade can collectively add points to SMUS Got Talent points for amazing prizes!</p>
  <a class="btn btn-primary" href="{% url 'spiritdashboard:register'%}" role="button">Create an Account</a>
</div>

    <h4>Login</h4>
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>        
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'spiritdashboard:login' %}?next={{ next }}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Login</button>
    </form>
    <br>

    {# Assumes you setup the password_reset view in your URLconf #}
    <p><a href="">Forgot your password?</a></p>
{% endblock %}

spiritdashboard/templates/spiritdashboard/privacy_policy.html
{% extends 'spiritdashboard/base.html' %}

{% block content %}
    <h4>Privacy Policy</h4>

<p>Effective date: February 11, 2019</p>


<p>SMUS Go ("us", "we", or "our") operates the https://smusgo.com website (hereinafter referred to as the "Service").</p>

<p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://smusgo.com</p>


<h5>Information Collection And Use</h5>

<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

<h6>Types of Data Collected</h6>

<p><b>Personal Data</b></p>

<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

<ul>
<li>Email address</li><li>First name and last name</li><li>Cookies and Usage Data</li>
</ul>

<p><b>Usage Data</b></p>

<p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

<p><b>Tracking & Cookies Data</b></p>
<p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
<p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. You can learn more how to manage cookies in the <a href="https://privacypolicies.com/blog/how-to-delete-cookies/">Browser Cookies Guide</a>.</p>
<p>Examples of Cookies we use:</p>
<ul>
    <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
    <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
    <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
</ul>

<h5>Use of Data</h5>
    
<p>SMUS Go uses the collected data for various purposes:</p>    
<ul>
    <li>To provide and maintain the Service</li>
    <li>To notify you about changes to our Service</li>
    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
    <li>To provide customer care and support</li>
    <li>To provide analysis or valuable information so that we can improve the Service</li>
    <li>To monitor the usage of the Service</li>
    <li>To detect, prevent and address technical issues</li>
</ul>

<h5>Transfer Of Data</h5>
<p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
<p>If you are located outside Canada and choose to provide information to us, please note that we transfer the data, including Personal Data, to Canada and process it there.</p>
<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
<p>SMUS Go will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

<h5>Disclosure Of Data</h5>

<h6>Legal Requirements</h6>
<p>SMUS Go may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
    <li>To comply with a legal obligation</li>
    <li>To protect and defend the rights or property of SMUS Go</li>
    <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
    <li>To protect the personal safety of users of the Service or the public</li>
    <li>To protect against legal liability</li>
</ul>

<h5>Security Of Data</h5>
<p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

<h5>Service Providers</h5>
<p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

<h6>Analytics</h6>
<p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>    
<ul>
        <li>
        <p><strong>Google Analytics</strong></p>
        <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
        <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>                <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p>
    </li>
                                </ul>


<h5>Links To Other Sites</h5>
<p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>


<h5>Children's Privacy</h5>
<p>Our Service does not address anyone under the age of 18 ("Children").</p>
<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>


<h5>Changes To This Privacy Policy</h5>
<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>


<h5>Contact Us</h5>
<p>If you have any questions about this Privacy Policy, please contact us:</p>
<ul>
        <li>By email: contact@smusgo.com</li>
          
        </ul>
{% endblock %}

spiritdashboard/templates/spiritdashboard/register.html
{% extends 'spiritdashboard/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h4>Register an Account</h4>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Register</button>
  </form>
{% endblock %}